apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: database
      title: Database
      description: Database Options
      items:
        - name: postgres_type
          type: select_one
          title: Postgres
          default: embedded_postgres
          items:
            - name: embedded_postgres
              title: Embedded Postgres
            - name: external_postgres
              title: External Postgres
        - name: embedded_postgres_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: external_postgres_host
          title: Postgres Host
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres"}}'
          type: text
          default: postgres
        - name: external_postgres_port
          title: Postgres Port
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres"}}'
          type: text
          default: "5432"
        - name: external_postgres_user
          title: Postgres Username
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres"}}'
          type: text
          required: true
        - name: external_postgres_password
          title: Postgres Password
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres"}}'
          type: password
          required: true
        - name: external_postgres_db
          title: Postgres Database
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres"}}'
          type: text
          default: sentry

        - name: redis_type
          type: select_one
          title: Redis
          default: embedded_redis
          items:
            - name: embedded_redis
              title: Embedded Redis
            - name: external_redis
              title: External Redis
        - name: embedded_redis_password
          hidden: true
          type: password
          value: "{{repl RandomString 10}}"      
        - name: embedded_redis_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: external_redis_host
          title: Redis Host
          when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
          type: text
          default: redis
        - name: external_redis_port
          title: Redis Port
          when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
          type: text
          default: "6379"
        - name: external_redis_user
          title: Redis Username
          when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
          type: text
        - name: external_redis_password
          title: Redis Password
          when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
          type: password
          required: true
    - name: smtp_settings
      title: SMTP Settings
      description: Configure SMTP Settings
      items:
        - name: enable_smtp
          title: Enable SMTP
          help_text: Enable SMTP
          type: bool
          default: "0"
        - name: smtp_host
          title: SMTP Hostname
          help_text: Set SMTP Hostname
          type: text
          when: repl{{ ConfigOptionEquals "enable_smtp" "1" }}
        - name: smtp_port
          title: SMTP Port
          help_text: Set SMTP Port
          type: text
          when: repl{{ ConfigOptionEquals "enable_smtp" "1" }}
        - name: smtp_user
          title: SMTP User
          help_text: Set SMTP User
          type: text
          when: repl{{ ConfigOptionEquals "enable_smtp" "1" }}
        - name: smtp_password
          title: SMTP Password
          type: password
          default: 'password'
          when: repl{{ ConfigOptionEquals "enable_smtp" "1" }}
    - name: influxdb_settings
      title: InfluxDB Settings
      items:
        - name: deploy-influxdb
          title: Deploy InfluxDB?
          type: bool
          default: "1"
        - name: influxdb_password
          hidden: true
          type: password
          value: "{{repl RandomString 10}}"
        - name: influxdb_token
          hidden: true
          type: password
          value: "{{repl RandomString 20}}"    
    - name: minio_settings
      title: MINIO Settings
      description: Configure minio Settings
      items:
        - name: deploy-minio
          title: Deploy MinIO?
          type: bool
          default: "1" 
        - name: embedded_minio_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}" 
    - name: rabbitmq_settings
      title: RabbitMQ Settings
      items:
        - name: deploy-rabbit
          title: Deploy RabbitMQ?
          type: bool
          default: "1"
        - name: rabbitmq_password
          hidden: true
          type: password
          value: "{{repl RandomString 16}}"
        - name: rabbitmq_erlang_cookie
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"      
   

