---
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: example-preflight-checks
spec:
  collectors:
    - postgres:
        exclude: 'repl{{ ConfigOptionEquals "postgres_type" "embedded_postgres" }}'
        collectorName: postrges-check
#        uri: 'postgresql://user:password@hostname:5432/dbname?sslmode=require'
        uri: 'postgresql://repl{{ ConfigOption "external_postgres_user"}}:repl{{ ConfigOption "external_postgres_password"}}@repl{{ ConfigOption "external_postgres_host"}}:repl{{ ConfigOption "external_postgres_port"}}/repl{{ ConfigOption "external_postgres_db"}}?sslmode=require'
    - run:
        exclude: repl{{ ConfigOptionEquals "enable_smtp" "0" }}
        collectorName: "run-ping"
        image: busybox:1
        name: ping.txt
        namespace: default
        command: ["ping"]
        args: ["-w", "10", "-c", "10", "-i", "0.3", '{{repl ConfigOption "smtp_host"}}']
        imagePullPolicy: IfNotPresent    
  analyzers:
    - postgres:
        exclude: 'repl{{ ConfigOptionEquals "postgres_type" "embedded_postgres" }}'
        strict: 'repl{{  eq (LicenseFieldValue "licenseType") "prod" }}'
        checkName: Postgress Connection Test
        collectorName: postrges-check
        outcomes:
          - fail:
              when: connected == false
              message: Cannot connect to the Postgres server, please check [their docs](https://www.postgresql.org/docs/) for more help.
          - pass:
              message: The Postgres server is ready
    - textAnalyze:
        exclude: repl{{ ConfigOptionEquals "enable_smtp" "0" }}
        checkName: "run-ping"
        fileName: ping.txt/run-ping.log
        regexGroups: '(?P<Transmitted>\d+) packets? transmitted, (?P<Received>\d+) packets? received, (?P<Loss>\d+)(\.\d+)?% packet loss'
        outcomes:
          - pass:
              when: "Loss < 5"
              message: Able to connecto to SMTP host
          - fail:
              message: Unable to establish connectin with SMTP host